### ISSUE TITLE
отступы между блоками

### ISSUE THREAD

**Issue by dimaTarhan** [drotsyk/fitnes#4]
между блоками в green-menu должны быть отступы, чтобы текст и картинки одного блока не прикасались к другому

**Comment by drotsyk** [comment]
Они и так не прикасаются,я не вижу,скинь скрин,если ты имеешь ввиду колонки то они позиционировались justify-content: space-between и там есть отступы,да и в самих колонках между картинками и текстом есть отступы

**Comment by dimaTarhan** [comment]
да, там дело в br-х. я добавил текст и вот, что получилось! исправляй эти br-ы и я позакрываю замечания. а с адаптивкой что у тебя?

![image](https://user-images.githubusercontent.com/43604553/47963045-ab308000-e02e-11e8-8b74-e92533c28f05.png)
