### ISSUE TITLE
резиновые картинки

### ISSUE THREAD

**Issue by dimaTarhan** [drotsyk/fitnes#6]
картинки внутри блоков должны иметь ширину относительно родителя, тогда они будут менять размеры при изменении ширины окна или добавления контента.

P.S. Больше юзай % для блоков и контента внутри него!

**Comment by dimaTarhan** [comment]
Картинки в блоках. Ставь им % от родителя или заполняй ими блоки как на
главном экране, тогда они будут менять размер вместе с блоком или
показывать определенную часть

сб, 3 нояб. 2018 г. в 17:21, drotsyk <notifications@github.com>:

**Comment by dimaTarhan** [comment]
не знаю, ты исправил или я что-то напутал, но сейчас с картинками у тебя
все норм)

вс, 4 нояб. 2018 г. в 0:12, Дмитрий Тарган <diditar.com@gmail.com>:

**Comment by drotsyk** [comment]
не исправлял нечего
